# Generated by Django 4.1.1 on 2022-09-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Laptop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("off", models.IntegerField()),
                ("url", models.URLField()),
                ("cpu_manifacturer", models.CharField(blank=True, max_length=20)),
                ("cpu_serry", models.CharField(blank=True, max_length=20)),
                ("cpu_model", models.CharField(blank=True, max_length=20)),
                ("ram_capacity", models.CharField(blank=True, max_length=20)),
                ("ram_type", models.CharField(blank=True, max_length=20)),
                ("gpu_manifacturer", models.CharField(blank=True, max_length=20)),
                ("gpu_model", models.CharField(blank=True, max_length=20)),
                ("internal_sotrage_type", models.CharField(blank=True, max_length=50)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("optical_drive", models.CharField(blank=True, max_length=50)),
                ("connection_ports", models.CharField(blank=True, max_length=200)),
                ("usb2", models.CharField(blank=True, max_length=20)),
                ("usb3", models.CharField(blank=True, max_length=20)),
                ("battery", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mobile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_id", models.IntegerField(unique=True)),
                ("category", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=200)),
                ("brand", models.CharField(max_length=50)),
                ("price", models.IntegerField()),
                ("off", models.IntegerField()),
                ("url", models.URLField()),
                ("ram", models.CharField(blank=True, max_length=20)),
                ("cpu", models.CharField(blank=True, max_length=20)),
                ("size", models.CharField(blank=True, max_length=20)),
                ("resolution", models.CharField(blank=True, max_length=20)),
                ("storage", models.CharField(blank=True, max_length=20)),
                ("network", models.CharField(blank=True, max_length=20)),
                ("main_camera", models.CharField(blank=True, max_length=20)),
                ("selfie_camera", models.TextField(blank=True)),
                ("battery", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
